"""create devices and loans tables

Revision ID: 0d0e8b654860
Revises: 0001_users
Create Date: 2026-09-19 19:45:48.136947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d0e8b654860'
down_revision: Union[str, Sequence[str], None] = '0001_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=80), nullable=True),
    sa.Column('is_available', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('length(trim(device_type)) > 0', name='ck_devices_type'),
    sa.CheckConstraint('length(trim(name)) > 0', name='ck_devices_name'),
    sa.CheckConstraint('length(trim(serial_number)) > 0', name='ck_devices_serial'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_type'), ['device_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_is_available'), ['is_available'], unique=False)

    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('loan_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('return_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("(status = 'returned' AND return_date IS NOT NULL) OR (status != 'returned' AND return_date IS NULL)", name='ck_loans_return_status'),
    sa.CheckConstraint("status IN ('active', 'returned', 'overdue')", name='ck_loans_status'),
    sa.CheckConstraint('return_date IS NULL OR return_date >= loan_date', name='ck_loans_dates'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_loans_open_device', ['device_id'], unique=True, sqlite_where=sa.text("status IN ('active', 'overdue')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index('uq_loans_open_device', sqlite_where=sa.text("status IN ('active', 'overdue')"))
        batch_op.drop_index(batch_op.f('ix_loans_user_id'))
        batch_op.drop_index(batch_op.f('ix_loans_status'))
        batch_op.drop_index(batch_op.f('ix_loans_device_id'))

    op.drop_table('loans')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_is_available'))
        batch_op.drop_index(batch_op.f('ix_devices_device_type'))

    op.drop_table('devices')
    # ### end Alembic commands ###
